version: '2'
services:
    apdsampleapplication-app:
        image: apdsampleapplication
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://apdsampleapplication-mysql:3306/apdsampleapplication?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    apdsampleapplication-mysql:
        extends:
            file: mysql.yml
            service: apdsampleapplication-mysql
